import {
  BRANCH_PROVINCE_LIST,
  BRANCH_CITY_LIST,
  BRANCH_ALL_LIST,
  BRANCH_NEAR_LIST,
  BRANCH_SEARCH_HISTORY
} from '@/store/modules/branch'

export const S_KEYS = {
  BRANCH_PROVINCE_LIST,
  BRANCH_CITY_LIST,
  BRANCH_ALL_LIST,
  BRANCH_NEAR_LIST,
  BRANCH_SEARCH_HISTORY
}
export const L_KEYS = {}
